<?php

return [
    'uz' => [
        'select_language' => 'Foydalanish tilini tanlang',
        'enter_weight' => 'Vazningizni kiriting',
        'select_gender' => 'Jinsingizni tanlang',
        'enter_goal_weight' => 'Ko\'zlangan vaznni kiriting',
        'enter_tall' => 'Bo\'yingizni kiriting (santimetrlarda misol uchun: 168)',
        'enter_age' => 'Yoshingizni kiriting',
        'select_activity_type' => 'Aktivlik turini tanlang',
        'normal_weight_for_you' => 'Siz uchun taklif qilinadigan normal vazn oralig`i',
        'your_weight_is_small_than_normal' => 'Sizning vazningiz normal vazndan kichik. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_normal' => 'Sizning vazningiz normal vazn holatida. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_goal_weight' => 'Vazningiz ko`zlangan vazn bilan teng holatda!',
        'your_weight_is_small_than_goal_weight' => 'Vazningiz ko`zlangan vazndan kichikroq!',
        'language' => 'Til',
        'gender' => 'Jins',
        'tall' => 'Bo`y',
        'weight' => 'Vazn',
        'goal_weight' => 'Ko`zlangan vazn',
        'age' => 'Yosh',
        'activity_type' => 'Aktivlik',
        'man' => 'Erkak',
        'woman' => 'Ayol',
        'uz' => '🇺🇿 O\'zbekcha',
        'ru' => '🇷🇺 Ruscha',
        'confirm' => '✅ Tasdiqlash',
        'start_again' => '🔄 Boshidan boshlash',
        'daily_spend' => 'Kunlik kaloriya sarfingiz',
        'your_goal_weight_is_small_than_normal' => 'Sizning vazningiz normal vazn oralig`idan kichik . Sport bilan shug`illanishni tavfsiya qilamiz',
        'menu' => 'Menyu',
        'settings' => 'Sozlamalar',
        'support' => 'Support',
        'soon' => 'Tez orada',
        'daily_need' => 'Kunlik olishingiz kerak bo`lgan kaloriya',
        'back' => 'Orqaga',
        'your_earned_track_score' => '〽️Sizning to\'plagan ballingiz',
        'your_track_status' => '🔝Sizning natijalardagi holatingiz',
        'your_track_result_of_this_week' => '↔️Bu hafta ko\'rsatkichi',
        'track_result_day_not_entered' => '🤷‍♂️ Kiritilmagan',
        'track_result_day_full_followed' => '🤩 to\'liq amal qilindi',
        'track_result_day_partically_followed' => '🙂 qisman amal qilindi',
        'track_result_day_not_followed' => '☹️ amal qilinmadi',
        'track_status_not_calculated' => '❓',
        'track_status_unsatisfied' => 'qoniqarsiz',
        'track_status_satisfactory' => '🥉 qoniqarli',
        'track_status_good' => '🥈 yaxshi',
        'track_status_super' => '🥇 super',
        'for_this_day_how_did_you_follow' => "Bugun tavfsiya qilingan menyularga qay darajada amal qildingiz ? \n",
        'you_must_not_eat_until_tomorrow' => 'Esingizda bo`lsin 19:00 dan ertalabgacha hech narsa istemol qilish mumkin emas',
        'full_follow_a_diet' => '🤩 To\'liq amal qildim',
        'partially_follow_a_diet' => '🙂 qisman amal qildim',
        'did_not_follow_a_diet' => '☹️ amal qilmadim',
        'next_time_be_more_active' => "Siz 1 ball qo'lga kiritdingiz. \n\n" . "Keyingi safar yanada masuliyatli bo'ling va menyularga to'liq amal qiling 🙂",
        'next_time_also_be_active' => "Juda zo'r siz 2 ball qo'lga kiritdingiz. \n\n" . "Keyingi kunlarda ham shunday davom eting 🤩",
        'next_time_follow' => "Keyingi kun albatta menyularga qatiyan amal qiling.\n\n",
        'track_report_after_19_every_day' => 'Kunlik hisobotlar har kuni soat 19:00 dan keyin beriladi',
        'welcome_for_new_user' => "Sizni bizning Dieto botimizda ko'rishdan mamnunmiz\n\n" .
            "Bu bot sizga ozish yoki semirish uchun yordam beradi\n\n" .
            "Bu bot sizga quyidagi xizmatlarni taqdim etadi:\n" .
            "- ✅ Vazn yo'qotish yoki yig'ish uchun mos menyular\n" .
            "- ✅ Kunlik kaloriya hisob-kitobi\n" .
            "- ✅ Ovqat yoki mahsulot kaloriyasini aniqlash\n" .
            "- ✅ Har kuni ovqatlanishingizni nazorat qilish\n\n" .
            "Siz botdan tekin foydalanishingiz yoki premium obuna orqali qo'shimcha xizmatlardan foydalanishingiz mumkin.",
        'welcome_to_home_for_old_user' => 'Bosh sahifa',
        'welcome_menus_page' => 'Kerakli menyuni tanlang',
        'welcome_settings_page' => 'Profil',
        'enter_weight_of_right_now' => 'Hozirgi vazningizni kiriting ',
        'weight_changing_history_stored' => 'Saqlandi',
        'tap_on_button_which_you_want_to_change' => 'O\'zgartirmoqchi bo\'lgan ma\'lumotingiz ustiga bosing 👇👇👇',
        'enter_the_correct_format' => 'To\'g\'ri formatda kiriting',
        'enter_the_correct_format_of_tall' => 'Bo\'yingizni to\'g\'ri formatda kiriting (misol uchun: 168)',
        'buy_premium_message' => "Premium obuna sotib olish uchun quyidagi kartaga kerakli summani o'tqazishingiz va chekini va shaxsiy raqamingizni :bill_check_admin ga jo'natishingiz kerak.\n\n Bir oylik obuna narxi: <code>:premium_price</code> so'm \n\n Karta: <code>:card_number</code> \n Shaxsiy raqamingiz: <code>:chat_id</code>",
        'status_of_subscribe_premium' => "Siz <strong>Premium</strong> obunadasiz. \n\nAmal qilish muddati <strong>:premium_ending_date</strong> gacha",
        'status_of_subscribe_base' => "Siz <strong>Base</strong> obunadasiz.\n\n",
        'ai_calculated' => '✅Hisoblandi',
        'i_think_its' => 'Menimcha bu',
        'total_calories' => 'Umumiy kaloriyasi',
        'macros' => 'Ozuqaviy qiymati',
        'proteins' => 'Protein',
        'carbs' => 'Uglevodlar',
        'fats' => 'Yog\'',
        'ingredients' => 'Tarkibidagi mahsulotlar',
        'saved' => '✅Saqlandi',
        'special_menu_for_you' => 'siz uchun maxsus menyu',
        'daily_need_calories' => 'Kunlik yeyish kerak bo\'lgan kkaloriya',
        'rules_which_need_follow' => "Amal qilish kerak bo'lgan qoidalar",
        'for_more_menu_parts_buy_premium' => "Yana ham ko'proq menyularni olish uchun premium obunani sotib oling",
        'ai_calculating' => "Hisoblayabmiz...",
        'ai_comment' => "💬 Izoh berish",
        'ai_delete' => "➕ Yangi mahsulot",
        'ai_result_comment_desc' => "⚠️ Natijada xatolik bo'lsa Izoh berish tugmasini bosib qo'shimcha izoh yozing",
        'tell_me_about_this_product' => "Natijada xatolik mavjud bo'lsa qo'shimcha izoh yozing",
        'ai_result_is_correct' => "✅ Natija to'g'ri",
        'send_product_image_or_name' => "😒 Bu istemol qilinadigan mahsulot emas",
        'welcome_to_calc_ai_conversation' => "Siz ovqat yoki mahsulot kaloriyasini aniqlash menyusidasiz. \nOvqat .yoki mahsulot nomini kiriting yoki rasmini yuboring 👇👇👇",
        'your_calc_ai_attempts_count' => "Eslatma: Sizda <strong> :calc_ai_attempts_count </strong> ta urinish mavjud. Har bir urinishda yangi ovqat yoki mahsulotning kaloriyasini aniqlashingiz mumkin. Urinishlaringiz tugagach, qo'shimcha urinishlar uchun premium obunani sotib olishingiz kerak.",
        'your_calc_ai_attempts_is_over' => "Sizning barcha urinishlaringiz tugadi. Qo'shimcha urinishlar uchun premium obunani sotib olishingiz kerak. Premium xizmatini sotib olish uchun <strong> Premium sotib olish </strong> tugmasini bosing.",
        'this_result_of_ai_deleted' => "Natija o'chirilgan !",
        'sorry_this_calc_ai_conversation_deleted' => "Bu natija o'chirilgan",
        'group_link_text_for_woman' => "Ayollar uchun guruhimizga qo'shiling",
        'group_link_text_for_man' => "Erkaklar uchun guruhimizga qo'shiling",
        'enter_the_group' => "Guruhga qo'shilish",
        'language_changed' => "Foydalanish tili o'zgartirildi",
        'gender_selected' => "Jins saqlandi",
        'activity_type_selected' => "Aktivlik turi saqlandi",
        'language_saved' => 'Foydalanish turi saqlandi',
        'conguratulation_message_for_premium' => "Tabriklaymiz, siz 1 oylik premium obunaga ega bo'ldingiz. Botning barcha imkoniyatlaridan to'liq foydalanishingiz mumkin" . PHP_EOL . "Kunlik menyularni 'Menyular' bo'limidan olishingiz mumkin",
        'returned_to_base' => "Siz premium obunangiz o'chirildi. Obunani qayta tiklash uchun '👑 Premium sotib olish' tugmasini bosing",
        'welcome_to_my_results' => "Natijalar bo'limi",
        'calc_ai_conversation_closed_by_system' => "Suniy intelekt bilan muloqot yopildi",
        'entering_fio' => "Ismingizni kiriting"

    ],
    'ru' => [
        'select_language' => 'Выберите язык',
        'enter_weight' => 'Введите свой вес',
        'select_gender' => 'Выберите свой пол',
        'enter_goal_weight' => 'Введите свой намеченный вес',
        'enter_tall' => 'Введите свой рост (например, в сантиметрах: 168)',
        'enter_age' => 'Введите свой возраст',
        'select_activity_type' => 'Выберите тип активности',
        'normal_weight_for_you' => 'Рекомендуемый нормальный диапазон веса для вас',
        'your_weight_is_small_than_normal' => 'Ваш вес меньше нормы. Занимайтесь спортом. (Вы можете повторно ввести свой вес, если вы ввели его неправильно)',
        'your_weight_is_equal_to_normal' => 'Ваш вес находится в нормальном состоянии. Занимайтесь спортом. (Вы можете повторно ввести свой вес, если вы ввели его неправильно)',
        'your_weight_is_equal_to_goal_weight' => 'Ваш вес наравне с намеченным весом!',
        'your_weight_is_small_than_goal_weight' => 'Ваш вес меньше чем намеченный вес!',
        'language' => 'язык',
        'gender' => 'Пол',
        'tall' => 'Рост',
        'weight' => 'Вес',
        'goal_weight' => 'Намеченный вес',
        'age' => 'Возраст',
        'activity_type' => 'Активность',
        'man' => 'Мужчина',
        'woman' => 'Женщина',
        'uz' => 'уз Узбекский',
        'ru' => 'Ру Русский',
        'confirm' => '✅ Подтвердить',
        'start_again' => '🔄 Начать сначала',
        'daily_spend' => 'Ваш ежедневный расход калорий',
        'your_goal_weight_is_small_than_normal' => 'Ваш вес меньше нормального диапазона веса . Рекомендуем заниматься спортом',
        'menu' => 'Меню',
        'settings' => 'Настройки',
        'support' => 'Поддержка',
        'soon' => 'Скоро',
        'daily_need' => 'Калории, которые вы должны набирать ежедневно',
        'back' => 'Назад',
        'your_earned_track_score' => '〽Ваш набранный балл',
        'your_track_status' => '🔝Ваш статус в результатах',
        'your_track_result_of_this_week' => '↔️Индикатор этой недели',
        'track_result_day_not_entered' => '🤷‍♂️ Не включено',
        'track_result_day_full_followed' => '🤩 полностью выполнено',
        'track_result_day_partically_followed' => '🙂 частично выполнено',
        'track_result_day_not_followed' => '☹️ не выполнен',
        'track_status_not_calculated' => '❓',
        'track_status_unsatisfied' => 'неудовлетворительный',
        'track_status_satisfactory' => '🥉 удовлетворительный',
        'track_status_good' => '🥈 хорошо',
        'track_status_super' => '🥇 супер',
        'for_this_day_how_did_you_follow' => "Насколько хорошо вы следовали предписанному сегодня меню? ? \n",
        'you_must_not_eat_until_tomorrow' => 'Помните, что с 19: 00 до утра ничего нельзя есть',
        'full_follow_a_diet' => '🤩 полностью соблюдал',
        'partially_follow_a_diet' => '🙂 частично соблюдал',
        'did_not_follow_a_diet' => '☹️ не соблюдал',
        'next_time_be_more_active' => "Вы заработали 1 балл. \n\n" . "В следующий раз будьте более ответственными и полностью следуйте меню. 🙂",
        'next_time_also_be_active' => "Очень круто, вы получили 2 балла. \n\n" . "Продолжайте так же в последующие дни 🤩",
        'next_time_follow' => "На следующий день обязательно строго придерживайтесь меню.\n\n",
        'track_report_after_19_every_day' => 'Ежедневные отчеты предоставляются ежедневно после 19:00',
        'welcome_for_new_user' => "Мы рады видеть вас в нашем боте Dieto\n\n" .
            "Этот бот поможет вам похудеть или набрать вес\n\n" .
            "Этот бот предоставляет вам следующие услуги:\n" .
            "- ✅ Меню, подходящие для похудения или набора веса\n" .
            "- ✅ Ежедневный подсчет калорий\n" .
            "- ✅ Определение калорийности пищи или продукта\n" .
            "- ✅ Ежедневный контроль над своим питанием\n\n" .
            "Вы можете использовать бота бесплатно или воспользоваться дополнительными услугами по премиум-подписке.",
        'welcome_to_home_for_old_user' => 'Главная страница',
        'welcome_menus_page' => 'Выберите нужное меню',
        'welcome_settings_page' => 'Профиль',
        'enter_weight_of_right_now' => 'Введите свой текущий вес ',
        'weight_changing_history_stored' => 'Сохранено',
        'tap_on_button_which_you_want_to_change' => 'Нажмите на информацию, которую хотите изменить 👇👇👇',
        'enter_the_correct_format' => 'Введите в правильном формате',
        'enter_the_correct_format_of_tall' => 'Введите свой рост в правильном формате (например: 168)',
        'buy_premium_message' => "Чтобы купить премиум-подписку, вы должны перевести необходимую сумму на следующую карту и отправить чек и свой личный номер:bill_check_admin ну\n\n Стоимость ежемесячной подписки: <code>:premium_price</code> so'm \n\n Карта: <code>:card_number</code> \n Ваш личный номер: <code>:chat_id</code>",
        'status_of_subscribe_premium' => "Вы подписаны на <strong>Premium</strong>. \n\nСрок годности до <strong>:premium_ending_date</strong>",
        'status_of_subscribe_base' => "Вы подписаны на <strong>Base</strong> .\n\n",
        'ai_calculated' => '✅Рассчитано',
        'i_think_its' => 'Я думаю,это',
        'total_calories' => 'Всего калорий',
        'macros' => 'Пищевая ценность',
        'proteins' => 'Белок',
        'carbs' => 'Углеводы',
        'fats' => 'Жир',
        'ingredients' => 'Продукты в составе',
        'saved' => '✅Сохранено',
        'special_menu_for_you' => 'специальное меню для вас',
        'daily_need_calories' => 'Калории, которые нужно есть ежедневно',
        'rules_which_need_follow' => "Правила, которым нужно следовать",
        'for_more_menu_parts_buy_premium' => "Купите премиум-подписку, чтобы получить еще больше меню",
        'ai_calculating' => "Вычисляем...",
        'ai_comment' => "💬 Прокомментировать",
        'ai_delete' => "➕ Новый продукт",
        'ai_result_comment_desc' => "⚠️ Напишите дополнительный комментарий, нажав кнопку 'прокомментировать', если в результате возникла ошибка",
        'tell_me_about_this_product' => "Напишите дополнительный комментарий, если в результате возникла ошибка",
        'ai_result_is_correct' => "✅ Результат правильный",
        'send_product_image_or_name' => "😒 Это не съедобный продукт",
        'welcome_to_calc_ai_conversation' => "Вы находитесь в меню для определения калорийности еды или продукта. \n Введите название еды или продукта или отправьте фотографию 👇👇👇",
        'your_calc_ai_attempts_count' => "Примечание :у вас есть попытка <strong>: calc_ai_attempts_count </strong>. Вы можете определить калорийность новой пищи или продукта с каждой попытки. Когда ваши попытки будут завершены, вам нужно будет приобрести премиум-подписку для дополнительных попыток.",
        'your_calc_ai_attempts_is_over' => "Все ваши попытки окончены. Для дополнительных попыток вам необходимо приобрести премиум-подписку. Нажмите <strong> Premium buy </strong>, чтобы купить премиум-сервис.",
        'this_result_of_ai_deleted' => "Результат удален!",
        'sorry_this_calc_ai_conversation_deleted' => "Этот результат удален",
        'group_link_text_for_woman' => "Присоединяйтесь к нашей группе для женщин",
        'group_link_text_for_man' => "Присоединяйтесь к нашей мужской группе",
        'enter_the_group' => "Вступить в группу",
        'language_changed' => "Изменен язык использования",
        'gender_selected' => "Пол сохранен",
        'activity_type_selected' => "Тип активности сохранен",
        'language_saved' => 'Тип использования сохранен',
        'conguratulation_message_for_premium' => "Поздравляем, у вас есть премиум-подписка на 1 месяц. Вы можете в полной мере использовать все возможности бота" . PHP_EOL . "Вы можете получить ежедневные меню В разделе  меню",
        'returned_to_base' => "Ваша премиум-подписка была удалена. Нажмите кнопку 'купить👑 Premium', чтобы продлить подписку.",
        'welcome_to_my_results' => "Раздел результатов",
        'calc_ai_conversation_closed_by_system' => "Диалог с ИИ закрыт",
        'entering_fio' => "Введите свое имя"


    ],
];
