<?php

return [
    'uz' => [
        'select_language' => 'Foydalanish tilini tanlang',
        'enter_weight' => 'Vazningizni kiriting',
        'select_gender' => 'Jinsingizni tanlang',
        'enter_goal_weight' => 'Ko\'zlangan vaznni kiriting',
        'enter_tall' => 'Bo\'yingizni kiriting (santimetrlarda misol uchun: 168)',
        'enter_age' => 'Yoshingizni kiriting',
        'select_activity_type' => 'Aktivlik turini tanlang',
        'normal_weight_for_you' => 'Siz uchun taklif qilinadigan normal vazn oralig`i',
        'your_weight_is_small_than_normal' => 'Sizning vazningiz normal vazndan kichik. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_normal' => 'Sizning vazningiz normal vazn holatida. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_goal_weight' => 'Vazningiz ko`zlangan vazn bilan teng holatda!',
        'your_weight_is_small_than_goal_weight' => 'Vazningiz ko`zlangan vazndan kichikroq!',
        'language' => 'Til',
        'gender' => 'Jins',
        'tall' => 'Bo`y',
        'weight' => 'Vazn',
        'goal_weight' => 'Ko`zlangan vazn',
        'age' => 'Yosh',
        'activity_type' => 'Aktivlik',
        'man' => 'Erkak',
        'woman' => 'Ayol',
        'uz' => '🇺🇿 O\'zbekcha',
        'ru' => '🇷🇺 Ruscha',
        'confirm' => '✅ Tasdiqlash',
        'start_again' => '🔄 Boshidan boshlash',
        'daily_spend' => 'Kunlik kaloriya sarfingiz',
        'your_goal_weight_is_small_than_normal' => 'Sizning vazningiz normal vazn oralig`idan kichik . Sport bilan shug`illanishni tavfsiya qilamiz',
        'menu' => 'Menyu',
        'settings' => 'Sozlamalar',
        'support' => 'Support',
        'soon' => 'Tez orada',
        'daily_need' => 'Kunlik olishingiz kerak bo`lgan kaloriya',
        'back' => 'Orqaga',
        'your_earned_track_score' => '〽️Sizning to\'plagan ballingiz',
        'your_track_status' => '🔝Sizning natijalardagi holatingiz',
        'your_track_result_of_this_week' => '↔️Bu hafta ko\'rsatkichi',
        'track_result_day_not_entered' => '🤷‍♂️ Kiritilmagan',
        'track_result_day_full_followed' => '🤩 to\'liq amal qilindi',
        'track_result_day_partically_followed' => '🙂 qisman amal qilindi',
        'track_result_day_not_followed' => '☹️ amal qilinmadi',
        'track_status_not_calculated' => '❓',
        'track_status_unsatisfied' => 'qoniqarsiz',
        'track_status_satisfactory' => '🥉 qoniqarli',
        'track_status_good' => '🥈 yaxshi',
        'track_status_super' => '🥇 super',
        'for_this_day_how_did_you_follow' => "Bugun tavfsiya qilingan menyularga qay darajada amal qildingiz ? \n",
        'you_must_not_eat_until_tomorrow' => 'Esingizda bo`lsin 19:00 dan ertalabgacha hech narsa istemol qilish mumkin emas',
        'full_follow_a_diet' => '🤩 To\'liq amal qildim',
        'partially_follow_a_diet' => '🙂 qisman amal qildim',
        'did_not_follow_a_diet' => '☹️ amal qilmadim',
        'next_time_be_more_active' => "Siz 1 ball qo\'lga kiritdingiz. \n\n" . "Keyingi safar yanada masuliyatli bo\'ling va menyularga to\'liq amal qiling 🙂",
        'next_time_also_be_active' => "Juda zo\'r siz 2 ball qo\'lga kiritdingiz. \n\n" . "Keyingi kunlarda ham shunday davom eting 🤩",
        'next_time_follow' => "Keyingi kun albatta menyularga qatiyan amal qiling.\n\n",
        'track_report_after_19_every_day' => 'Kunlik hisobotlar har kuni soat 19:00 dan keyin beriladi',
        'welcome_for_new_user' => "Sizni bizning Dieto botimizda ko'rishdan mamnunmiz\n\n" .
            "Bu bot sizga ozish yoki semirish uchun yordam beradi\n\n" .
            "Bu bot sizga quyidagi xizmatlarni taqdim etadi:\n" .
            "- ✅ Vazn yo'qotish yoki yig'ish uchun mos menyular\n" .
            "- ✅ Kunlik kaloriya hisob-kitobi\n" .
            "- ✅ Ovqat yoki mahsulot kaloriyasini aniqlash\n" .
            "- ✅ Har kuni ovqatlanishingizni nazorat qilish\n\n" .
            "Siz botdan tekin foydalanishingiz yoki premium obuna orqali qo'shimcha xizmatlardan foydalanishingiz mumkin.",
        'welcome_to_home_for_old_user' => 'Bosh sahifa',
        'welcome_menus_page' => 'Kerakli menyuni tanlang',
        'welcome_settings_page' => 'Profil',
        'enter_weight_of_right_now' => 'Hozirgi vazningizni kiriting ',
        'weight_changing_history_stored' => 'Saqlandi',
        'tap_on_button_which_you_want_to_change' => 'O\'zgartirmoqchi bo\'lgan ma\'lumotingiz ustiga bosing 👇👇👇',
        'enter_the_correct_format' => 'To\'g\'ri formatda kiriting',
        'enter_the_correct_format_of_tall' => 'Bo\'yingizni to\'g\'ri formatda kiriting (misol uchun: 168)',
        'buy_premium_message' => "Premium obuna sotib olish uchun quyidagi kartaga kerakli summani o\'tqazishingiz va chekini va shaxsiy raqamingizni :bill_check_admin ga jo\'natishingiz kerak.\n\n Bir oylik obuna narxi: <code>:premium_price</code> so'm \n\n Karta: <code>:card_number</code> \n Shaxsiy raqamingiz: <code>:chat_id</code>",
        'status_of_subscribe_premium' => "Siz <strong>Premium</strong> obunadasiz. \n\n Obunangiz tugash sanasi :premium_ending_date",
        'status_of_subscribe_base' => "Siz <strong>Base</strong> obunadasiz.\n\n",
        'ai_calculated' => '✅Hisoblandi',
        'i_think_its' => 'Menimcha bu',
        'total_calories' => 'Umumiy kaloriyasi',
        'macros' => 'Ozuqaviy qiymati',
        'proteins' => 'Protein',
        'carbs' => 'Uglevodlar',
        'fats' => 'Yog\'',
        'ingredients' => 'Tarkibidagi mahsulotlar',
        'saved' => '✅Saqlandi',
        'welcome_to_calc_ai_conversation' => ''
    ],
    'ru' => [
        'select_language' => 'Foydalanish tilini tanlang',
        'enter_weight' => 'Vazningizni kiriting',
        'select_gender' => 'Jinsingizni tanlang',
        'enter_goal_weight' => 'Ko\'zlangan vaznni kiriting',
        'enter_tall' => 'Bo\'yingizni kiriting (santimetrlarda misol uchun: 168)',
        'enter_age' => 'Yoshingizni kiriting',
        'select_activity_type' => 'Aktivlik turini tanlang',
        'normal_weight_for_you' => 'Siz uchun taklif qilinadigan normal vazn oralig`i',
        'your_weight_is_small_than_normal' => 'Sizning vazningiz normal vazndan kichik. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_normal' => 'Sizning vazningiz normal vazn holatida. Sport bilan shug`ullaning. (Agar vazningizni noto`g`ri kiritgan bo`lsangiz qayta kiritishingiz mumkin)',
        'your_weight_is_equal_to_goal_weight' => 'Vazningiz ko`zlangan vazn bilan teng holatda!',
        'your_weight_is_small_than_goal_weight' => 'Vazningiz ko`zlangan vazndan kichikroq!',
        'language' => 'Til',
        'gender' => 'Jins',
        'tall' => 'Bo`y',
        'weight' => 'Vazn',
        'goal_weight' => 'Ko`zlangan vazn',
        'age' => 'Yosh',
        'activity_type' => 'Aktivlik',
        'man' => 'Erkak',
        'woman' => 'Ayol',
        'uz' => '🇺🇿 O\'zbekcha',
        'ru' => '🇷🇺 Ruscha',
        'confirm' => '✅ Tasdiqlash',
        'start_again' => '🔄 Boshidan boshlash',
        'daily_spend' => 'Kunlik kaloriya sarfingiz',
        'your_goal_weight_is_small_than_normal' => 'Sizning vazningiz normal vazn oralig`idan kichik . Sport bilan shug`illanishni tavfsiya qilamiz',
        'menu' => 'Menyu',
        'settings' => 'Sozlamalar',
        'support' => 'Support',
        'soon' => 'Tez orada',
        'daily_need' => 'Kunlik olishingiz kerak bo`lgan kaloriya',
        'back' => 'Orqaga',
        'your_earned_track_score' => '〽️Sizning to\'plagan ballingiz',
        'your_track_status' => '🔝Sizning natijalardagi holatingiz',
        'your_track_result_of_this_week' => '↔️Bu hafta ko\'rsatkichi',
        'track_result_day_not_entered' => '🤷‍♂️ Kiritilmagan',
        'track_result_day_full_followed' => '🤩 to\'liq amal qilindi',
        'track_result_day_partically_followed' => '🙂 qisman amal qilindi',
        'track_result_day_not_followed' => '☹️ amal qilinmadi',
        'track_status_not_calculated' => '❓',
        'track_status_unsatisfied' => 'qoniqarsiz',
        'track_status_satisfactory' => '🥉 qoniqarli',
        'track_status_good' => '🥈 yaxshi',
        'track_status_super' => '🥇 super',
        'for_this_day_how_did_you_follow' => "Bugun tavfsiya qilingan menyularga qay darajada amal qildingiz ? \n",
        'you_must_not_eat_until_tomorrow' => 'Esingizda bo`lsin 19:00 dan ertalabgacha hech narsa istemol qilish mumkin emas',
        'full_follow_a_diet' => '🤩 To\'liq amal qildim',
        'partially_follow_a_diet' => '🙂 qisman amal qildim',
        'did_not_follow_a_diet' => '☹️ amal qilmadim',
        'next_time_be_more_active' => "Siz 1 ball qo\'lga kiritdingiz. \n\n" . "Keyingi safar yanada masuliyatli bo\'ling va menyularga to\'liq amal qiling 🙂",
        'next_time_also_be_active' => "Juda zo\'r siz 2 ball qo\'lga kiritdingiz. \n\n" . "Keyingi kunlarda ham shunday davom eting 🤩",
        'next_time_follow' => "Keyingi kun albatta menyularga qatiyan amal qiling.\n\n",
        'track_report_after_19_every_day' => 'Kunlik hisobotlar har kuni soat 19:00 dan keyin beriladi',
        'welcome_for_new_user' => "Sizni bizning Dieto botimizda ko'rishdan mamnunmiz\n\n" .
            "Bu bot sizga ozish yoki semirish uchun yordam beradi\n\n" .
            "Bu bot sizga quyidagi xizmatlarni taqdim etadi:\n" .
            "- ✅ Vazn yo'qotish yoki yig'ish uchun mos menyular\n" .
            "- ✅ Kunlik kaloriya hisob-kitobi\n" .
            "- ✅ Ovqat yoki mahsulot kaloriyasini aniqlash\n" .
            "- ✅ Har kuni ovqatlanishingizni nazorat qilish\n\n" .
            "Siz botdan tekin foydalanishingiz yoki premium obuna orqali qo'shimcha xizmatlardan foydalanishingiz mumkin.",
        'welcome_to_home_for_old_user' => 'Bosh sahifa',
        'welcome_menus_page' => 'Kerakli menyuni tanlang',
        'welcome_settings_page' => 'Profil',
        'enter_weight_of_right_now' => 'Hozirgi vazningizni kiriting ',
        'weight_changing_history_stored' => 'Saqlandi',
        'tap_on_button_which_you_want_to_change' => 'O\'zgartirmoqchi bo\'lgan ma\'lumotingiz ustiga bosing 👇👇👇',
        'enter_the_correct_format' => 'To\'g\'ri formatda kiriting',
        'enter_the_correct_format_of_tall' => 'Bo\'yingizni to\'g\'ri formatda kiriting (misol uchun: 168)',
        'buy_premium_message' => "Premium obuna sotib olish uchun quyidagi kartaga kerakli summani o\'tqazishingiz va chekini va shaxsiy raqamingizni :bill_check_admin ga jo\'natishingiz kerak.\n\n Bir oylik obuna narxi: <code>:premium_price</code> so'm \n\n Karta: <code>:card_number</code> \n Shaxsiy raqamingiz: <code>:chat_id</code>",
        'status_of_subscribe_premium' => "Siz <strong>Premium</strong> obunadasiz. \n\n Obunangiz tugash sanasi :premium_ending_date",
        'status_of_subscribe_base' => "Siz <strong>Base</strong> obunadasiz.\n\n",
        'ai_calculated' => '✅Hisoblandi',
        'i_think_its' => 'Menimcha bu',
        'total_calories' => 'Umumiy kaloriyasi',
        'macros' => 'Ozuqaviy qiymati',
        'proteins' => 'Protein',
        'carbs' => 'Uglevodlar',
        'fats' => 'Yog\'',
        'ingredients' => 'Tarkibidagi mahsulotlar',
        'saved' => '✅Saqlandi'
    ],
];
